import { Service, Project, Testimonial, BlogPost, TeamMember, NavLink, Stat } from "@/types";

export const COMPANY_INFO = {
  name: "Swift Professional Solutions Limited",
  tagline: "Your Partner in Digital Excellence",
  description: "Swift Professional Solutions Limited is a newly established ICT company in Abuja, Nigeria, dedicated to delivering innovative and reliable technology solutions to help businesses thrive in the digital age.",
  email: "Admin@Swiftpsl.com",
  phone: "+234 803 741 5509",
  phoneRaw: "2348037415509",
  whatsappMessage: "Hello Swift Professional Solutions, I'd like to enquire about your services.",
  address: "House 12b Paradise Estate, Katampe, Abuja, Nigeria",
  rcNumber: "RC-2026001",
  foundedYear: 2026,
};

export const NAV_LINKS: NavLink[] = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Portfolio", href: "/portfolio" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

export const SERVICES: Service[] = [
  {
    id: "1",
    slug: "it-infrastructure",
    title: "IT Infrastructure",
    shortDescription: "Robust and scalable IT infrastructure solutions for modern businesses.",
    fullDescription: "We design, implement, and maintain enterprise-grade IT infrastructure that forms the backbone of your digital operations. From network architecture to server management, our team ensures your systems are secure, reliable, and optimized for performance.",
    icon: "Server",
    features: [
      "Network Design & Implementation",
      "Server Virtualization",
      "Data Center Solutions",
      "Infrastructure Monitoring",
      "Disaster Recovery Planning",
      "24/7 Technical Support",
    ],
    processSteps: [
      { title: "Assessment", description: "We analyze your current infrastructure and identify improvement areas." },
      { title: "Design", description: "Our architects create a customized infrastructure blueprint aligned with your business goals." },
      { title: "Implementation", description: "We deploy the solution with minimal disruption to your operations." },
      { title: "Support", description: "Ongoing monitoring and support ensure optimal performance." },
    ],
  },
  {
    id: "2",
    slug: "software-development",
    title: "Software Development",
    shortDescription: "Custom software solutions tailored to your business requirements.",
    fullDescription: "Our experienced development team creates bespoke software solutions that address your unique business challenges. From web applications to enterprise systems, we deliver scalable, secure, and user-friendly software that drives business growth.",
    icon: "Code",
    features: [
      "Web Application Development",
      "Mobile App Development",
      "Enterprise Software",
      "API Development & Integration",
      "Database Design",
      "Software Maintenance",
    ],
    processSteps: [
      { title: "Requirements Gathering", description: "We work closely with you to understand your business needs and objectives." },
      { title: "Planning", description: "Our team creates a detailed project plan including timelines and milestones." },
      { title: "Development", description: "We build your solution using modern technologies and best practices." },
      { title: "Testing & Deployment", description: "Rigorous testing ensures quality before seamless deployment." },
    ],
  },
  {
    id: "3",
    slug: "cybersecurity",
    title: "Cybersecurity",
    shortDescription: "Comprehensive security solutions to protect your digital assets.",
    fullDescription: "In an era of increasing cyber threats, our cybersecurity services provide comprehensive protection for your business. We offer vulnerability assessments, penetration testing, security audits, and incident response to safeguard your data and systems.",
    icon: "Shield",
    features: [
      "Vulnerability Assessment",
      "Penetration Testing",
      "Security Audits",
      "Incident Response",
      "Security Awareness Training",
      "Compliance Management",
    ],
    processSteps: [
      { title: "Discovery", description: "We identify your assets and potential vulnerabilities." },
      { title: "Analysis", description: "Our experts assess risks and prioritize security measures." },
      { title: "Implementation", description: "We deploy appropriate security solutions." },
      { title: "Monitoring", description: "Continuous monitoring and regular updates protect against emerging threats." },
    ],
  },
  {
    id: "4",
    slug: "cloud-solutions",
    title: "Cloud Solutions",
    shortDescription: "Scalable cloud services for modern business operations.",
    fullDescription: "Transform your business with our cloud solutions. We help organizations migrate to the cloud, optimize cloud infrastructure, and implement hybrid cloud strategies that enhance flexibility, reduce costs, and improve collaboration.",
    icon: "Cloud",
    features: [
      "Cloud Migration",
      "Cloud Architecture Design",
      "AWS/Azure/Google Cloud",
      "Hybrid Cloud Solutions",
      "Cloud Security",
      "Cost Optimization",
    ],
    processSteps: [
      { title: "Evaluation", description: "We assess your requirements and recommend the best cloud strategy." },
      { title: "Planning", description: "Our team creates a migration roadmap with clear milestones." },
      { title: "Migration", description: "We execute the migration with minimal downtime." },
      { title: "Optimization", description: "Ongoing optimization ensures cost-effectiveness and performance." },
    ],
  },
  {
    id: "5",
    slug: "it-consulting",
    title: "IT Consulting",
    shortDescription: "Strategic IT guidance to drive business transformation.",
    fullDescription: "Our IT consulting services help businesses leverage technology to achieve their strategic objectives. We provide expert advice on digital transformation, IT strategy, technology selection, and process optimization.",
    icon: "Briefcase",
    features: [
      "Digital Transformation",
      "IT Strategy Planning",
      "Technology Assessment",
      "Process Optimization",
      "Vendor Management",
      "IT Governance",
    ],
    processSteps: [
      { title: "Consultation", description: "We understand your business goals and current state." },
      { title: "Analysis", description: "Our experts analyze your technology landscape and identify opportunities." },
      { title: "Strategy", description: "We develop a comprehensive IT strategy aligned with your business objectives." },
      { title: "Execution", description: "We support the implementation of recommended solutions." },
    ],
  },
  {
    id: "6",
    slug: "managed-it-support",
    title: "Managed IT Support",
    shortDescription: "Reliable managed IT services to keep your business running smoothly.",
    fullDescription: "Our managed IT support services provide proactive monitoring, maintenance, and support for your IT infrastructure. We act as your virtual IT department, ensuring your systems are always up and running efficiently.",
    icon: "Headphones",
    features: [
      "24/7 Help Desk Support",
      "Proactive Monitoring",
      "System Maintenance",
      "User Support",
      "Patch Management",
      "Remote Support",
    ],
    processSteps: [
      { title: "Onboarding", description: "We assess your environment and establish monitoring protocols." },
      { title: "Setup", description: "Our team configures tools and establishes support processes." },
      { title: "Support", description: "We provide ongoing support and proactive maintenance." },
      { title: "Reporting", description: "Regular reports keep you informed about system health and issues." },
    ],
  },
];

export const PROJECTS: Project[] = [
  {
    id: "1",
    slug: "enterprise-resource-planning",
    title: "Enterprise Resource Planning System",
    category: "Software",
    description: "Custom ERP solution for a leading manufacturing company in Nigeria.",
    fullDescription: "We developed a comprehensive ERP system that streamlined operations for a major manufacturing company. The solution integrated inventory management, finance, HR, and production planning into a single unified platform.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
    tags: ["React", "Node.js", "PostgreSQL", "AWS"],
    client: "Manufacturing Corp Nigeria",
    year: "2026",
  },
  {
    id: "2",
    slug: "fintech-mobile-app",
    title: "Fintech Mobile Application",
    category: "Web",
    description: "Secure mobile banking app with advanced features for a Nigerian bank.",
    fullDescription: "We built a secure, user-friendly mobile banking application featuring bill payments, fund transfers, savings goals, and real-time notifications. The app serves over 100,000 active users.",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=600&fit=crop",
    tags: ["React Native", "TypeScript", "AWS Amplify", "Biometrics"],
    client: "Heritage Bank",
    year: "2026",
  },
  {
    id: "3",
    slug: "hospital-information-system",
    title: "Hospital Information System",
    category: "Software",
    description: "Comprehensive HIS for a multi-specialty hospital in Abuja.",
    fullDescription: "We developed a complete hospital management system covering patient records, appointments, billing, pharmacy, and laboratory management. The system improved operational efficiency by 40%.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop",
    tags: ["Angular", "Java", "MySQL", "HL7"],
    client: "Reddington Hospital",
    year: "2026",
  },
  {
    id: "4",
    slug: "e-commerce-platform",
    title: "E-Commerce Platform",
    category: "Web",
    description: "Full-featured online store for a major retail brand.",
    fullDescription: "We built a scalable e-commerce platform with product catalog, shopping cart, payment integration, inventory management, and analytics dashboard. The platform handles over 10,000 daily orders.",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop",
    tags: ["Next.js", "Shopify", "Stripe", "Redis"],
    client: "Shoprite Nigeria",
    year: "2026",
  },
  {
    id: "5",
    slug: "network-security-audit",
    title: "Network Security Infrastructure",
    category: "Security",
    description: "Complete security overhaul for a financial institution.",
    fullDescription: "We conducted a comprehensive security assessment and implemented a robust security infrastructure including firewall, IDS/IPS, SIEM, and endpoint protection for a leading Nigerian bank.",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=600&fit=crop",
    tags: ["Fortinet", "Splunk", "Palo Alto", "CrowdStrike"],
    client: "First Bank Nigeria",
    year: "2026",
  },
  {
    id: "6",
    slug: "cloud-migration",
    title: "Cloud Migration",
    category: "Infrastructure",
    description: "Seamless migration to AWS for a logistics company.",
    fullDescription: "We successfully migrated on-premise infrastructure to AWS, implementing a hybrid cloud architecture that improved scalability and reduced operational costs by 35%.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop",
    tags: ["AWS", "Docker", "Kubernetes", "Terraform"],
    client: "Logistics Corp Nigeria",
    year: "2026",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Dr. Adedamola Okonkwo",
    company: "Reddington Hospital",
    role: "Chief Medical Director",
    quote: "Swift Professional Solutions transformed our hospital operations with their comprehensive IT solution. Their team was professional, knowledgeable, and delivered beyond our expectations.",
    rating: 5,
  },
  {
    id: "2",
    name: "Mr. Chukwuemeka Nwachukwu",
    company: "Heritage Bank",
    role: "Head of Digital Banking",
    quote: "The fintech mobile app they developed has been instrumental in our digital transformation journey. User adoption exceeded 150% of our targets.",
    rating: 5,
  },
  {
    id: "3",
    name: "Mrs. Folake Adeyemi",
    company: "Shoprite Nigeria",
    role: "E-Commerce Director",
    quote: "Our online sales increased by 300% after launching the new e-commerce platform. The team's attention to detail and technical expertise is unmatched.",
    rating: 5,
  },
  {
    id: "4",
    name: "Mr. Olumide Williams",
    company: "Manufacturing Corp Nigeria",
    role: "CEO",
    quote: "The ERP system has revolutionized how we operate. Inventory turnover improved by 45% and we have real-time visibility into all our operations.",
    rating: 5,
  },
  {
    id: "5",
    name: "Mr. Ibrahim Suleiman",
    company: "First Bank Nigeria",
    role: "CISO",
    quote: "Their cybersecurity expertise is world-class. They identified vulnerabilities we didn't know existed and secured our infrastructure comprehensively.",
    rating: 5,
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    slug: "digital-transformation-nigeria-2024",
    title: "Digital Transformation in Nigeria: Trends and Opportunities",
    excerpt: "Explore the latest digital transformation trends shaping Nigerian businesses and how organizations can leverage technology for growth.",
    content: "Full article content here...",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop",
    author: "Dr. Sarah Johnson",
    date: "January 15, 2026",
    category: "Digital Transformation",
    readTime: "8 min read",
  },
  {
    id: "2",
    slug: "cybersecurity-best-practices",
    title: "Essential Cybersecurity Best Practices for Nigerian Businesses",
    excerpt: "Learn the critical cybersecurity measures every business in Nigeria should implement to protect against evolving cyber threats.",
    content: "Full article content here...",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=500&fit=crop",
    author: "Mr. Emmanuel Adeyemi",
    date: "January 10, 2026",
    category: "Cybersecurity",
    readTime: "6 min read",
  },
  {
    id: "3",
    slug: "cloud-computing-benefits",
    title: "Why Cloud Computing is the Future of Nigerian Business",
    excerpt: "Discover how cloud computing is enabling Nigerian businesses to scale, reduce costs, and improve operational efficiency.",
    content: "Full article content here...",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=500&fit=crop",
    author: "Mrs. Grace Oluwole",
    date: "January 5, 2026",
    category: "Cloud Solutions",
    readTime: "7 min read",
  },
];

export const TEAM: TeamMember[] = [
  {
    id: "1",
    name: "Dr. Oladipo Adeyemi",
    role: "Chief Executive Officer",
    image: "/images/team/ceo.jpg",
    linkedin: "https://linkedin.com",
  },
  {
    id: "2",
    name: "Mrs. Chidinma Nwankwo",
    role: "Chief Technology Officer",
    image: "/images/team/cto.jpg",
    linkedin: "https://linkedin.com",
  },
  {
    id: "3",
    name: "Mr. Tunde Bakare",
    role: "Head of Operations",
    image: "/images/team/operations.jpg",
    linkedin: "https://linkedin.com",
  },
  {
    id: "4",
    name: "Ms. Amara Okonkwo",
    role: "Head of Business Development",
    image: "/images/team/bd.jpg",
    linkedin: "https://linkedin.com",
  },
];

export const STATS: Stat[] = [
  { value: 5, suffix: "+", label: "Clients" },
  { value: 8, suffix: "+", label: "Projects" },
  { value: 1, suffix: "+", label: "Years Experience" },
  { value: 100, suffix: "%", label: "Client Satisfaction" },
];

export const WHY_CHOOSE_US = [
  {
    title: "Local Expertise",
    description: "Deep understanding of the Nigerian business landscape and regulatory environment.",
    icon: "MapPin",
  },
  {
    title: "Fresh Approach",
    description: "Modern solutions leveraging the latest technologies and best practices.",
    icon: "Award",
  },
  {
    title: "24/7 Support",
    description: "Round-the-clock technical support to keep your business running smoothly.",
    icon: "Clock",
  },
  {
    title: "Certified Professionals",
    description: "Team of certified experts with international qualifications.",
    icon: "BadgeCheck",
  },
  {
    title: "Scalable Solutions",
    description: "Solutions that grow with your business needs.",
    icon: "TrendingUp",
  },
  {
    title: "Competitive Pricing",
    description: "High-quality services at cost-effective rates.",
    icon: "PiggyBank",
  },
];

export const PORTFOLIO_CATEGORIES = ["all", "Web", "Infrastructure", "Software", "Security"] as const;

export const SERVICE_OPTIONS = SERVICES.map((s) => ({ value: s.slug, label: s.title }));
